language: rust

matrix:
  fast_finish: true
  include:
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

    - rust: stable
      os: osx
      env: TARGET=x86_64-apple-darwin

cache:
  timeout: 360
  cargo: true

before_cache:
  - chmod -R a+r $HOME/.cargo

env:
  global:
    - CRATE_NAME=mdbook

script:
  - cargo test --all
  - cargo test --all --no-default-features

before_deploy:
  - sh ci/before_deploy.sh
  - target/"$TARGET"/release/mdbook build book-example

deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file_glob: true
    file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
    skip_cleanup: true
    on:
      condition: "$TRAVIS_RUST_VERSION = stable"
      tags: true
  - provider: pages
    skip-cleanup: true
    local-dir: book-example/book
    github-token: "$GITHUB_OAUTH_TOKEN"
    keep-history: false
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = "linux" && $TRAVIS_RUST_VERSION = "stable"

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never
